# This is a basic workflow to help you get started with Actions

name: Update DB

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
             python-version: 3.9
             
      #- name: Install git
      # uses: srt32/git-actions@v0.0.3
             
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install selenium dill
          
      - name: Setup Chromedriver
        uses: nanasess/setup-chromedriver@v1.0.5
        
      - name: Start XVFB
        run: |
            sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        
      - name: Run fetch_runs.py
        run: pipenv run python fetch_runs.py 
        env:
          DISPLAY: :99
          
      - name: Run update_playes.py
        run: pipenv run python update_players.py 
               
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
